language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - coverage run tests/tests.py

after_success:
  - codecov

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - preprocesador-set-de-datos